// Generated by CoffeeScript 1.8.0
(function() {
  var Log, Schema, logSchema;

  Schema = require('mongoose').Schema;

  logSchema = new Schema({
    createDate: {
      type: Number,
      "default": Date.now()
    },
    method: String,
    params: {},
    member: {
      type: Schema.Types.ObjectId,
      ref: "Member"
    }
  });

  Log = db.model('Log', logSchema);

  module.exports = Log;

}).call(this);

//# sourceMappingURL=log.js.map
