// Generated by CoffeeScript 1.8.0
(function() {
  var Schema, VerificationCode, verificationCodeSchema;

  Schema = require("mongoose").Schema;

  verificationCodeSchema = new Schema({
    code: String,
    mobile: String,
    expire: Number
  });

  verificationCodeSchema.index({
    mobile: 1
  });

  VerificationCode = db.model("VerificationCode", verificationCodeSchema);

  module.exports = VerificationCode;

}).call(this);
