// Generated by CoffeeScript 1.8.0
(function() {
  var Schema, WeixinCustomer, customerSchema;

  Schema = require('mongoose').Schema;

  customerSchema = new Schema({
    ent: {
      type: Schema.Types.ObjectId,
      ref: "Ent"
    },
    subscribe: Number,
    openid: String,
    nickname: String,
    sex: Number,
    city: String,
    country: String,
    province: String,
    language: String,
    headimgurl: String,
    subscribe_time: Number,
    unionid: String
  });

  customerSchema.index;

  WeixinCustomer = db.model('WeixinCustomer', customerSchema);

}).call(this);
