// Generated by CoffeeScript 1.8.0
(function() {
  var PriceCtrl, config, id, mongoose, uri;

  mongoose = require("mongoose");

  config = require("./../config/config.json");

  uri = "mongodb://" + config.db.host + ":" + config.db.port + "/" + config.db.database;

  global.db = mongoose.createConnection(uri);

  PriceCtrl = require("./../control/priceCtrl");

  id = "54a36e74d62713a35a8e728c";

  PriceCtrl.deductInventory(id, 1, function(err, res) {
    return console.log(err, res);
  });

}).call(this);
