// Generated by CoffeeScript 1.8.0
(function() {
  var a, aaa, b, _;

  _ = require('underscore');

  a = {
    a: 1,
    b: 2
  };

  b = {
    c: 3,
    d: 4
  };

  aaa = _.extend(a, b);

  console.log(aaa);

}).call(this);

//# sourceMappingURL=test.js.map
