// Generated by CoffeeScript 1.8.0
(function() {
  var QRcodeCtrl, fn;

  QRcodeCtrl = require('./../control/qrcodeCtrl');

  fn = function(err, res) {
    return console.log(err, res);
  };

  QRcodeCtrl.generateCode(fn, 123123);

}).call(this);

//# sourceMappingURL=test.js.map
