// Generated by CoffeeScript 1.8.0
(function() {
  var SpecCtrl, express, router;

  express = require("express");

  router = express.Router();

  SpecCtrl = require("./../control/specCtrl");

  router.post("/save", function(request, response) {
    var productId, specs;
    productId = request.body.id;
    specs = request.body.spec != null ? JSON.parse(request.body.spec) : [];
    console.log(specs);
    return SpecCtrl.save(productId, specs, function(err, res) {
      if (err) {
        return response.json({
          error: 1,
          errMsg: err.message
        });
      } else {
        return response.json({
          error: 0,
          data: res
        });
      }
    });
  });

  router.get("/list", function(request, response) {
    var productId;
    productId = request.query.id;
    return SpecCtrl.list(productId, function(err, res) {
      if (err) {
        return response.json({
          error: 1,
          errMsg: err.message
        });
      } else {
        return response.json({
          error: 0,
          data: res
        });
      }
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=spec.js.map
