// Generated by CoffeeScript 1.8.0
(function() {
  var LogCtrl, TokenCtrl, async;

  async = require('async');

  TokenCtrl = require('./tokenCtrl');

  LogCtrl = (function() {
    function LogCtrl() {}

    LogCtrl.save = function(method, params, token, fn) {
      return async.auto({
        GetMember: function(cb) {
          return TokenCtrl.findToken(token, function(err, res) {
            return cb(err, res);
          });
        },
        SaveLog: function(cb, results) {
          var log;
          if (results.GetMember != null) {
            log = new Log({
              method: method,
              params: params,
              member: results.GetMember.member._id
            });
            return log.save(function(err, res) {
              return cb(err, res);
            });
          } else {
            return cb(null, null);
          }
        }
      }, function(err, results) {
        return fn(err, results.SaveLog);
      });
    };

    return LogCtrl;

  })();

}).call(this);

//# sourceMappingURL=logCtrl.js.map
