// Generated by CoffeeScript 1.8.0
(function() {
  var NewsCtrl;

  NewsCtrl = (function() {
    var News, async;

    function NewsCtrl() {}

    async = require("async");

    News = require("./../model/news");

    NewsCtrl.save = function(ent, title, content, fn) {
      var news;
      news = new News({
        ent: ent,
        title: title,
        content: content
      });
      return news.save(function(err, res) {
        return fn(err, res);
      });
    };

    NewsCtrl.update = function(id, title, content, fn) {
      return News.findByIdAndUpdate(id, {
        $set: {
          title: title,
          content: content
        }
      }, function(err, res) {
        return fn(err, res);
      });
    };

    NewsCtrl.list = function(page, pageSize, ent, fn) {
      return async.auto({
        totalSize: function(cb) {
          return News.count({
            ent: ent
          }, function(err, count) {
            return cb(err, count);
          });
        },
        getNews: function(cb) {
          return News.find({
            ent: ent
          }).skip(page * pageSize).limit(pageSize).exec(function(err, res) {
            return cb(err, res);
          });
        }
      }, function(err, results) {
        if (err) {
          return fn(err);
        } else {
          return fn(null, {
            totalSize: results.totalSize,
            news: results.getNews
          });
        }
      });
    };

    return NewsCtrl;

  })();

  module.exports = NewsCtrl;

}).call(this);

//# sourceMappingURL=newsCtrl.js.map
