// Generated by CoffeeScript 1.8.0
(function() {
  var QRcodeCtrl, request;

  request = require('request');

  QRcodeCtrl = (function() {
    function QRcodeCtrl() {}

    QRcodeCtrl.generateCode = function(fn, code, width, logo) {
      var form;
      if (width == null) {
        width = 200;
      }
      form = {
        string: code,
        width: width,
        logo: logo
      };
      return request.post({
        url: "http://api.uihoo.com/qrcode/qrcode.http.php",
        form: form
      }, function(err, httpResponse, body) {
        var data, res;
        if (err) {
          return fn(err, null);
        } else {
          if (body !== "") {
            res = JSON.parse(body);
          }
          data = res != null ? res.base64 : void 0;
          data = data != null ? data.replace(/\r\n/g, "") : void 0;
          return fn(null, data);
        }
      });
    };

    return QRcodeCtrl;

  })();

  module.exports = QRcodeCtrl;

}).call(this);

//# sourceMappingURL=qrcodeCtrl.js.map
