// Generated by CoffeeScript 1.8.0
(function() {
  var SpecCtrl;

  SpecCtrl = (function() {
    var Spec, async, saveSpec;

    function SpecCtrl() {}

    Spec = require("./../model/spec");

    async = require("async");

    saveSpec = function(spec) {
      return function(cb) {
        var s;
        if (spec._id != null) {
          return Spec.findByIdAndUpdate(spec._id, {
            $set: {
              name: spec.name,
              product: spec.product
            }
          }, function(err, res) {
            return cb(err, res);
          });
        } else {
          s = new Spec(spec);
          return s.save(function(err, res) {
            return cb(err, res);
          });
        }
      };
    };

    SpecCtrl.save = function(productId, specs, fn) {
      var funcArr, spec;
      funcArr = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = specs.length; _i < _len; _i++) {
          spec = specs[_i];
          spec.product = productId;
          _results.push(saveSpec(spec));
        }
        return _results;
      })();
      return async.parallel(funcArr, function(err, results) {
        return fn(err, results);
      });
    };

    SpecCtrl.list = function(productId, fn) {
      return Spec.find({
        product: productId
      }, function(err, results) {
        return fn(err, results);
      });
    };

    return SpecCtrl;

  })();

  module.exports = SpecCtrl;

}).call(this);

//# sourceMappingURL=specCtrl.js.map
