// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinCustomerCtrl;

  WeixinCustomerCtrl = (function() {
    var CustomerCtrl, WeixinCustomer, async;

    function WeixinCustomerCtrl() {}

    WeixinCustomer = require("./../model/weixinCustomer");

    CustomerCtrl = require("./customerCtrl");

    async = require("async");

    WeixinCustomerCtrl.save = function(ent, subscribe, openid, nickname, sex, city, country, province, language, headimgurl, subscribe_time, unionid, fn) {
      return async.auto({
        findCustomer: function(cb) {
          return WeixinCustomer.findOneAndUpdate({
            ent: ent,
            openid: openid
          }, {
            $set: {
              subscribe: subscribe,
              nickname: nickname,
              sex: sex,
              city: city,
              country: country,
              province: province,
              language: language,
              headimgurl: headimgurl,
              subscribe_time: subscribe_time
            }
          }, function(err, res) {
            return cb(err, res);
          });
        },
        saveCustomer: [
          "findCustomer", function(cb, results) {
            var customer;
            customer = results.findCustomer;
            if (customer != null) {
              return cb(null, customer);
            } else {
              customer = new WeixinCustomer({
                ent: ent,
                subscribe: subscribe,
                openid: openid,
                nickname: nickname,
                sex: sex,
                city: city,
                country: country,
                province: province,
                language: language,
                headimgurl: headimgurl,
                subscribe_time: subscribe_time
              });
              return customer.save(function(err, res) {
                return cb(err, res);
              });
            }
          }
        ]
      }, function(err, results) {
        return fn(err, results.saveCustomer);
      });
    };

    WeixinCustomerCtrl.detail = function(ent, openid, fn) {
      return WeixinCustomer.findOne({
        ent: ent,
        openid: openid
      }).lean().exec(function(err, res) {
        if (err != null) {
          return fn(err);
        } else {
          if (res != null) {
            res.isWeixin = true;
          }
          return fn(null, res);
        }
      });
    };

    return WeixinCustomerCtrl;

  })();

  module.exports = WeixinCustomerCtrl;

}).call(this);
