// Generated by CoffeeScript 1.8.0
(function() {
  var WeixinCustomerCtrl;

  WeixinCustomerCtrl = (function() {
    var CustomerCtrl, WeixinCustomer, async;

    function WeixinCustomerCtrl() {}

    WeixinCustomer = require("./../model/weixinCustomer");

    CustomerCtrl = require("./customerCtrl");

    async = require("async");

    WeixinCustomerCtrl.save = function(ent, subscribe, openid, nickname, sex, city, country, province, language, headimgurl, subscribe_time, unionid, fn) {
      var customer;
      customer = new WeixinCustomer({
        ent: ent,
        subscribe: subscribe,
        openid: openid,
        nickname: nickname,
        sex: sex,
        city: city,
        country: country,
        province: province,
        language: language,
        headimgurl: headimgurl,
        subscribe_time: subscribe_time,
        unionid: unionid
      });
      return customer.save(function(err, res) {
        return fn(err, res);
      });
    };

    WeixinCustomerCtrl.detail = function(ent, openid, fn) {
      return WeixinCustomer.findOne({
        ent: ent,
        openid: openid
      }, function(err, res) {
        return fn(err, res);
      });
    };

    return WeixinCustomerCtrl;

  })();

  module.exports = WeixinCustomerCtrl;

}).call(this);
