// Generated by CoffeeScript 1.8.0
(function() {
  var DBLog;

  DBLog = (function() {
    function DBLog() {}

    DBLog.saveLog = function(req, res, next) {
      var obj, _;
      _ = require('underscore');
      obj = _.extend(req.query, req.body);
      console.log(obj);
      return next();
    };

    return DBLog;

  })();

  module.exports = DBLog;

}).call(this);

//# sourceMappingURL=dbLog.js.map
