// Generated by CoffeeScript 1.8.0
(function() {
  var TokenCtrl, VerfiyRequest, urlVerfiy,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  TokenCtrl = require('./../control/tokenCtrl');

  urlVerfiy = require('./../config/urlVerfiy.json');

  VerfiyRequest = (function() {
    function VerfiyRequest() {}

    VerfiyRequest.verfiy = function(req, res, next) {
      var token, url, _ref, _ref1;
      url = req.url.split(/\?/)[0];
      if (__indexOf.call(urlVerfiy, url) >= 0) {
        return next();
      } else {
        token = ((_ref = req.body) != null ? _ref.token : void 0) || ((_ref1 = req.query) != null ? _ref1.token : void 0);
        if (token != null) {
          return TokenCtrl.findToken(token, function(err, result) {
            if (result != null) {
              return next();
            } else {
              return res.json({
                error: 1,
                errMsg: "verify failed"
              });
            }
          });
        } else {
          return res.json({
            error: 1,
            errMsg: "verify failed"
          });
        }
      }
    };

    return VerfiyRequest;

  })();

  module.exports = VerfiyRequest;

}).call(this);

//# sourceMappingURL=verfiyRequest.js.map
